# Generated by Django 5.0.6 on 2026-05-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bursaries', '__first__'),
        ('institutions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sponsor_type', models.CharField(choices=[('bursary_provider', 'Bursary Provider'), ('institution', 'Institution'), ('partner', 'Other Partner')], max_length=20)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('company_registration', models.CharField(blank=True, help_text='SA company reg number', max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20, unique=True)),
                ('monthly_price_zar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_price_zar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority_boost', models.PositiveSmallIntegerField(default=10, help_text='Higher = more prominent placement')),
                ('max_listings', models.PositiveSmallIntegerField(default=1)),
                ('has_featured_card', models.BooleanField(default=False)),
                ('has_homepage_banner', models.BooleanField(default=False)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_direct_messaging', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sponsorship_plans',
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('amount_paid_zar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bursary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='bursaries.bursary')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='institutions.institution')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='sponsorships.sponsor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsorships.sponsorshipplan')),
            ],
            options={
                'db_table': 'sponsorships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='view', help_text='view | apply | save', max_length=20)),
                ('referrer', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='sponsorships.sponsorship')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sponsorship_clicks',
                'indexes': [models.Index(fields=['sponsorship', 'timestamp'], name='sponsorship_sponsor_b42131_idx')],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(help_text='Where on the app it was shown — e.g. "bursary_list_top"', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='sponsorships.sponsorship')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sponsorship_impressions',
                'indexes': [models.Index(fields=['sponsorship', 'timestamp'], name='sponsorship_sponsor_c93528_idx')],
            },
        ),
    ]
