# Generated by Django 5.0.6 on 2026-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('institution_name', models.CharField(max_length=200)),
                ('student_background', models.TextField()),
                ('key_achievements', models.TextField(blank=True)),
                ('why_this_course', models.TextField(blank=True)),
                ('why_this_institution', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('warm', 'Warm & Personal'), ('confident', 'Confident'), ('humble', 'Humble & Earnest')], default='professional', max_length=20)),
                ('language', models.CharField(default='en', max_length=5)),
                ('content', models.TextField(blank=True, help_text='The generated letter')),
                ('revision_count', models.PositiveSmallIntegerField(default=0)),
                ('is_finalised', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'motivation_letters',
                'ordering': ['-updated_at'],
            },
        ),
    ]
