"""
Seed municipal, district and international scholarships available to SA students for 2026.

Run:  python manage.py shell < scripts/seed_bursaries_municipal_international.py
"""
from datetime import date
from apps.bursaries.models import Bursary


MORE = [
    # ── Metro / municipal bursaries ───────────────────────────────────
    {
        'name': 'City of Johannesburg Bursary 2026',
        'provider': 'City of Johannesburg',
        'description': 'Bursary for residents of Johannesburg studying scarce-skills disciplines at a SA public institution.',
        'field': 'any', 'funding_type': 'full',
        'coverage': ['tuition', 'books'],
        'province': 'GP',
        'eligibility': 'Johannesburg resident (proof of address). SA citizen. Grade 12 ≥60% average. Household income ≤ R350 000. Studying scarce-skills qualification (Engineering, Health, IT, Finance).',
        'application_url': 'https://www.joburg.org.za/services_/Pages/City-Services/Bursaries.aspx',
        'application_deadline': date(2026, 1, 31),
        'min_grade_average': 60,
        'max_household_income': 350000,
    },
    {
        'name': 'City of Cape Town Bursary 2026',
        'provider': 'City of Cape Town',
        'description': 'Bursary for residents of the City of Cape Town studying disciplines aligned with city service needs.',
        'field': 'any', 'funding_type': 'full',
        'coverage': ['tuition', 'books'],
        'province': 'WC',
        'eligibility': 'Cape Town resident (proof of address). SA citizen. ≥60% average. Studying disciplines aligned with municipal needs (Engineering, Town Planning, Finance, Environmental Sciences).',
        'application_url': 'https://www.capetown.gov.za/Family%20and%20home/education-and-research-materials/Bursaries',
        'application_deadline': date(2026, 2, 28),
        'min_grade_average': 60,
    },
    {
        'name': 'eThekwini Municipality Bursary 2026',
        'provider': 'eThekwini Municipality',
        'description': 'Bursary for Durban residents studying engineering, finance and other priority disciplines.',
        'field': 'any', 'funding_type': 'full',
        'coverage': ['tuition', 'books'],
        'province': 'KZN',
        'eligibility': 'eThekwini resident. SA citizen. ≥60% Grade 12 average. Household income ≤ R350 000.',
        'application_url': 'https://www.durban.gov.za/pages/residents/bursaries',
        'application_deadline': date(2026, 1, 31),
        'min_grade_average': 60,
        'max_household_income': 350000,
    },
    {
        'name': 'City of Tshwane Bursary 2026',
        'provider': 'City of Tshwane',
        'description': 'Bursary for Pretoria / Tshwane residents in scarce-skills disciplines.',
        'field': 'any', 'funding_type': 'full',
        'coverage': ['tuition'],
        'province': 'GP',
        'eligibility': 'Tshwane resident. SA citizen. ≥60% Grade 12 average. Financial need.',
        'application_url': 'https://www.tshwane.gov.za/?page_id=11430',
        'application_deadline': date(2026, 2, 28),
        'min_grade_average': 60,
    },
    {
        'name': 'Ekurhuleni Metro Bursary 2026',
        'provider': 'City of Ekurhuleni',
        'description': 'Bursary for Ekurhuleni residents studying priority disciplines.',
        'field': 'any', 'funding_type': 'full',
        'coverage': ['tuition'],
        'province': 'GP',
        'eligibility': 'Ekurhuleni resident. SA citizen. ≥60% Grade 12 average. Financial need.',
        'application_url': 'https://www.ekurhuleni.gov.za/',
        'application_deadline': date(2026, 2, 28),
        'min_grade_average': 60,
    },
    {
        'name': 'Buffalo City Metro Bursary 2026',
        'provider': 'Buffalo City Metropolitan Municipality',
        'description': 'Bursary for East London / Buffalo City residents in scarce-skills disciplines.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'EC',
        'eligibility': 'Buffalo City resident. SA citizen. Financial need.',
        'application_url': 'http://www.buffalocity.gov.za/',
        'application_deadline': date(2026, 3, 31),
    },
    {
        'name': 'Nelson Mandela Bay Municipality Bursary 2026',
        'provider': 'Nelson Mandela Bay Municipality',
        'description': 'Bursary for NMB (Gqeberha) residents studying engineering, science, finance.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'EC',
        'eligibility': 'Nelson Mandela Bay resident. SA citizen. ≥60% Grade 12 average.',
        'application_url': 'https://www.nelsonmandelabay.gov.za/',
        'application_deadline': date(2026, 3, 31),
        'min_grade_average': 60,
    },
    {
        'name': 'Mangaung Metro Bursary 2026',
        'provider': 'Mangaung Metropolitan Municipality',
        'description': 'Bursary for Bloemfontein / Mangaung residents.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'FS',
        'eligibility': 'Mangaung resident. SA citizen. Financial need.',
        'application_url': 'http://www.mangaung.co.za/',
        'application_deadline': date(2026, 3, 31),
    },

    # ── District bursaries ────────────────────────────────────────────
    {
        'name': 'OR Tambo District Municipality Bursary 2026',
        'provider': 'OR Tambo District Municipality',
        'description': 'District bursary for OR Tambo District residents (Mthatha area).',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'EC',
        'eligibility': 'OR Tambo District resident. SA citizen. ≥60% Grade 12. Financial need.',
        'application_url': 'https://www.ortambodm.gov.za/',
        'application_deadline': date(2026, 1, 31),
        'min_grade_average': 60,
    },
    {
        'name': 'Sekhukhune District Bursary 2026',
        'provider': 'Sekhukhune District Municipality',
        'description': 'District bursary for residents of Sekhukhune District in Limpopo.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'LP',
        'eligibility': 'Sekhukhune District resident. SA citizen. Financial need.',
        'application_url': 'https://www.sekhukhune.gov.za/',
        'application_deadline': date(2026, 2, 28),
    },
    {
        'name': 'uMgungundlovu District Bursary 2026',
        'provider': 'uMgungundlovu District Municipality',
        'description': 'District bursary for uMgungundlovu (Pietermaritzburg) residents.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'KZN',
        'eligibility': 'uMgungundlovu District resident. SA citizen. ≥55% average.',
        'application_url': 'http://www.umdm.gov.za/',
        'application_deadline': date(2026, 2, 28),
        'min_grade_average': 55,
    },
    {
        'name': 'Capricorn District Bursary 2026',
        'provider': 'Capricorn District Municipality',
        'description': 'District bursary for Polokwane / Capricorn District residents.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'LP',
        'eligibility': 'Capricorn District resident. SA citizen.',
        'application_url': 'https://www.cdm.org.za/',
        'application_deadline': date(2026, 2, 28),
    },
    {
        'name': 'West Rand District Bursary 2026',
        'provider': 'West Rand District Municipality',
        'description': 'District bursary for West Rand (Krugersdorp/Westonaria/Randfontein) residents.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'GP',
        'eligibility': 'West Rand District resident. SA citizen.',
        'application_url': 'https://www.wrdm.gov.za/',
        'application_deadline': date(2026, 3, 31),
    },
    {
        'name': 'iLembe District Bursary 2026',
        'provider': 'iLembe District Municipality',
        'description': 'District bursary for KZN North Coast residents (Stanger, Ballito).',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'KZN',
        'eligibility': 'iLembe District resident. SA citizen.',
        'application_url': 'https://www.ilembe.gov.za/',
        'application_deadline': date(2026, 2, 28),
    },
    {
        'name': 'Vhembe District Bursary 2026',
        'provider': 'Vhembe District Municipality',
        'description': 'District bursary for Vhembe (Thohoyandou, Musina) residents.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'LP',
        'eligibility': 'Vhembe District resident. SA citizen. Financial need.',
        'application_url': 'https://www.vhembe.gov.za/',
        'application_deadline': date(2026, 2, 28),
    },
    {
        'name': 'Waterberg District Bursary 2026',
        'provider': 'Waterberg District Municipality',
        'description': 'District bursary for Waterberg (Mokopane/Modimolle) residents.',
        'field': 'any', 'funding_type': 'partial',
        'coverage': ['tuition'],
        'province': 'LP',
        'eligibility': 'Waterberg District resident. SA citizen.',
        'application_url': 'https://www.waterberg.gov.za/',
        'application_deadline': date(2026, 3, 31),
    },

    # ── International scholarships available to SA students ────────────
    {
        'name': 'Chevening Scholarship 2026',
        'provider': 'UK Foreign, Commonwealth & Development Office',
        'description': 'Fully-funded Masters scholarship at any UK university. Award covers tuition, monthly stipend, travel, visa and arrival allowance.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel'],
        'province': 'ALL',
        'eligibility': 'SA citizen with completed undergraduate degree (≥70% average typically). Minimum 2 years (2 800 hours) work experience. Leadership track record. Accepted unconditionally to 3 different UK universities for the same one-year Masters programme.',
        'application_url': 'https://www.chevening.org/scholarship/south-africa/',
        'application_deadline': date(2026, 11, 7),
        'min_grade_average': 70,
    },
    {
        'name': 'Commonwealth Scholarships 2026',
        'provider': 'Commonwealth Scholarship Commission UK',
        'description': 'Masters and PhD scholarships for Commonwealth citizens (including SA) to study at UK universities.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel'],
        'province': 'ALL',
        'eligibility': 'Commonwealth citizen. Completed undergrad with strong distinction (typically 1st-class). Financial need.',
        'application_url': 'https://cscuk.fcdo.gov.uk/scholarships/',
        'application_deadline': date(2026, 10, 31),
        'min_grade_average': 70,
    },
    {
        'name': 'Fulbright Foreign Student Program 2026',
        'provider': 'US Department of State / IIE',
        'description': 'Masters and PhD scholarships for SA students to study in the United States.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel', 'health'],
        'province': 'ALL',
        'eligibility': 'SA citizen with completed undergrad (≥65% / GPA 3.0+). Strong leadership profile and commitment to returning to SA after study.',
        'application_url': 'https://za.usembassy.gov/education-culture/fulbright/',
        'application_deadline': date(2026, 6, 30),
        'min_grade_average': 65,
    },
    {
        'name': 'DAAD Scholarship 2026',
        'provider': 'German Academic Exchange Service',
        'description': 'Masters and PhD scholarships for SA students to study in Germany.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel', 'health'],
        'province': 'ALL',
        'eligibility': 'SA citizen with completed undergraduate degree (≥65% / German "good" grade). Accepted into a German master\'s/PhD programme. Some German language proficiency helpful.',
        'application_url': 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
        'application_deadline': date(2026, 10, 31),
        'min_grade_average': 65,
    },
    {
        'name': 'Erasmus Mundus Scholarship 2026',
        'provider': 'European Union (Erasmus+)',
        'description': 'Fully-funded joint Masters programmes at multiple EU universities.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel', 'health'],
        'province': 'ALL',
        'eligibility': 'SA citizen with completed undergrad (≥65% average). Apply directly to one of the joint EMJM programmes.',
        'application_url': 'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters-scholarships',
        'application_deadline': date(2026, 1, 16),
        'min_grade_average': 65,
    },
    {
        'name': 'Australia Awards Scholarship 2026',
        'provider': 'Australian Government',
        'description': 'Fully-funded long-term study award for SA students to study at Australian universities (priority sectors).',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel'],
        'province': 'ALL',
        'eligibility': 'SA citizen with completed undergrad. Demonstrated leadership and intent to return to SA.',
        'application_url': 'https://www.dfat.gov.au/people-to-people/australia-awards/scholarships',
        'application_deadline': date(2026, 4, 30),
        'min_grade_average': 65,
    },
    {
        'name': 'Schwarzman Scholars 2026',
        'provider': 'Schwarzman Scholars / Tsinghua University',
        'description': 'One-year Master of Global Affairs at Tsinghua University, China. Full scholarship.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel'],
        'province': 'ALL',
        'eligibility': 'SA citizen aged 18-28. Completed undergraduate degree by Aug 2026 with strong record. English proficiency.',
        'application_url': 'https://www.schwarzmanscholars.org/admissions/',
        'application_deadline': date(2026, 9, 24),
        'min_grade_average': 70,
    },
    {
        'name': 'Rhodes Scholarship 2026',
        'provider': 'Rhodes Trust',
        'description': 'Postgraduate scholarship at Oxford University, UK. Two years funded.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel'],
        'province': 'ALL',
        'eligibility': 'SA citizen aged 19-25 with first-class undergraduate degree. Outstanding intellect, character, leadership, commitment to service.',
        'application_url': 'https://www.rhodeshouse.ox.ac.uk/scholarships/',
        'application_deadline': date(2026, 6, 30),
        'min_grade_average': 75,
    },
    {
        'name': 'Gates Cambridge Scholarship 2026',
        'provider': 'Bill & Melinda Gates Foundation / University of Cambridge',
        'description': 'Postgraduate scholarship at the University of Cambridge for outstanding international students.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel'],
        'province': 'ALL',
        'eligibility': 'SA citizen with first-class undergrad degree. Strong intellectual ability, leadership and commitment to improving the lives of others.',
        'application_url': 'https://www.gatescambridge.org/apply/',
        'application_deadline': date(2026, 10, 15),
        'min_grade_average': 75,
    },
    {
        'name': 'MasterCard Foundation Scholars at Cambridge 2026',
        'provider': 'Mastercard Foundation / University of Cambridge',
        'description': 'Postgraduate scholarship at Cambridge for African students.',
        'field': 'any', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'stipend', 'travel', 'mentorship'],
        'province': 'ALL',
        'eligibility': 'African citizen with strong undergrad record (≥70%). Commitment to giving back to Africa.',
        'application_url': 'https://www.cambridgetrust.org/scholarships/',
        'application_deadline': date(2026, 12, 5),
        'min_grade_average': 70,
    },
    {
        'name': 'JN Tata Endowment Scholarship 2026',
        'provider': 'JN Tata Endowment',
        'description': 'Loan scholarship for postgraduate study abroad (USA, UK, Europe, Asia).',
        'field': 'any', 'funding_type': 'loan',
        'coverage': ['tuition'],
        'province': 'ALL',
        'eligibility': 'Indian-descent SA citizen with completed undergrad. Accepted into a postgraduate programme abroad.',
        'application_url': 'https://www.jntataendowment.org/',
        'application_deadline': date(2026, 3, 31),
        'min_grade_average': 65,
    },

    # ── Additional national bursaries ──────────────────────────────────
    {
        'name': 'Sasol Inzalo Foundation Bursary 2026',
        'provider': 'Sasol Inzalo Foundation',
        'description': 'Comprehensive scholarship for top-achieving Grade 12s in Maths and Science to study STEM at SA universities.',
        'field': 'science', 'funding_type': 'scholarship',
        'coverage': ['tuition', 'accommodation', 'books', 'stipend', 'mentorship', 'laptop'],
        'province': 'ALL',
        'eligibility': 'SA citizen. Top performance in Grade 12 Maths (≥80%) and Physical Sciences (≥80%). Studying STEM at SA university.',
        'application_url': 'https://www.sasolinzalofoundation.org.za/',
        'application_deadline': date(2026, 4, 30),
        'min_grade_average': 80,
    },
    {
        'name': 'Engineers Without Borders SA Bursary 2026',
        'provider': 'Engineers Without Borders South Africa',
        'description': 'Bursary for female engineering students with commitment to sustainable development.',
        'field': 'engineering', 'funding_type': 'partial',
        'coverage': ['tuition', 'mentorship'],
        'province': 'ALL',
        'eligibility': 'SA female citizen, studying engineering at NQF 7+. Demonstrated commitment to community service.',
        'application_url': 'https://www.ewb-sa.org/',
        'application_deadline': date(2026, 6, 30),
    },
    {
        'name': 'Tomorrow Trust Bursary 2026',
        'provider': 'Tomorrow Trust',
        'description': 'Holistic education support for orphaned and vulnerable students at SA universities.',
        'field': 'any', 'funding_type': 'full',
        'coverage': ['tuition', 'accommodation', 'books', 'mentorship'],
        'province': 'ALL',
        'eligibility': 'Orphaned or vulnerable SA citizen. ≥65% Grade 12 average. Demonstrated resilience.',
        'application_url': 'https://www.tomorrow.org.za/',
        'application_deadline': date(2026, 9, 30),
        'min_grade_average': 65,
    },
    {
        'name': 'Studietrust Bursary 2026',
        'provider': 'Studietrust',
        'description': 'Bursary fund for high-potential students from disadvantaged backgrounds.',
        'field': 'any', 'funding_type': 'full',
        'coverage': ['tuition', 'accommodation', 'books', 'mentorship'],
        'province': 'ALL',
        'eligibility': 'SA citizen, household income ≤ R250 000. ≥65% Grade 12 average. Accepted at SA public university.',
        'application_url': 'https://www.studietrust.org.za/',
        'application_deadline': date(2026, 9, 30),
        'min_grade_average': 65,
        'max_household_income': 250000,
    },
    {
        'name': 'Ikusasa Student Financial Aid Programme (ISFAP) 2026',
        'provider': 'ISFAP',
        'description': 'Holistic funding programme for the "missing middle" (household income R350k-R600k) studying scarce skills.',
        'field': 'any', 'funding_type': 'full',
        'coverage': ['tuition', 'accommodation', 'books', 'stipend', 'mentorship'],
        'province': 'ALL',
        'eligibility': 'SA citizen, household income R350 000 – R600 000 (the "missing middle"). Studying scarce-skills disciplines.',
        'application_url': 'https://www.isfap.org.za/',
        'application_deadline': date(2026, 1, 31),
        'max_household_income': 600000,
    },
    {
        'name': 'SAICA Hope Factory Bursary 2026',
        'provider': 'SAICA / Hope Factory',
        'description': 'Bursary for students from disadvantaged backgrounds pursuing CA(SA) pathway.',
        'field': 'business', 'funding_type': 'full',
        'coverage': ['tuition', 'mentorship'],
        'province': 'ALL',
        'eligibility': 'SA citizen, financial need. Studying BCom Accounting (CA stream).',
        'application_url': 'https://www.thehopefactory.co.za/',
        'application_deadline': date(2026, 5, 31),
    },
]


created = 0
updated = 0
for b in MORE:
    obj, made = Bursary.objects.get_or_create(
        name=b['name'],
        defaults={**b, 'is_active': True},
    )
    if made:
        created += 1
    else:
        for k, v in b.items():
            setattr(obj, k, v)
        obj.is_active = True
        obj.save()
        updated += 1

total = Bursary.objects.filter(is_active=True).count()
print(f'Added: {created}    Updated: {updated}    Total bursaries: {total}')

from collections import Counter
print('\nBy province:')
for p, n in Counter(
    Bursary.objects.filter(is_active=True).values_list('province', flat=True)
).most_common():
    print(f'  {p:<5} {n}')
print('\nBy funding type:')
for ft, n in Counter(
    Bursary.objects.filter(is_active=True).values_list('funding_type', flat=True)
).most_common():
    print(f'  {ft:<12} {n}')
