# Generated by Django 5.0.6 on 2026-05-07 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('url', 'URL'), ('pdf', 'PDF Upload'), ('text', 'Pasted Text')], max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('source_filename', models.CharField(blank=True, max_length=300)),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='import_jobs/pdfs/%Y/%m/')),
                ('institution_short_name', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('ready', 'Ready for review'), ('saved', 'Saved to database'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('parsed_courses', models.JSONField(blank=True, default=list)),
                ('saved_course_ids', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_import_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
