# Generated by Django 5.0.6 on 2026-05-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('state', models.CharField(choices=[('idle', 'Idle (showing menu)'), ('awaiting_marks', 'Waiting for marks input'), ('awaiting_photo', 'Waiting for report photo'), ('awaiting_bursary_pick', 'Waiting for bursary number'), ('awaiting_uni_pick', 'Waiting for university name'), ('chatting_ai', 'Chatting with AI')], default='idle', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_sessions',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=4)),
                ('body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappsession')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
