# Generated by Django 5.0.6 on 2026-05-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('sharing', 'Sharing Room'), ('bachelor', 'Bachelor Flat'), ('one_bed', '1 Bedroom'), ('two_bed', '2 Bedroom')], max_length=20)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nsfas_accredited', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nearby_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_accommodation', to='institutions.institution')),
            ],
            options={
                'db_table': 'accommodation',
                'ordering': ['price_per_month'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodation.accommodation')),
            ],
            options={
                'db_table': 'accommodation_images',
                'ordering': ['order'],
            },
        ),
    ]
