# Generated by Django 5.0.6 on 2026-05-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('deadline_type', models.CharField(choices=[('application', 'Application Deadline'), ('bursary', 'Bursary Deadline'), ('nsfas', 'NSFAS Deadline'), ('late_application', 'Late Application'), ('other', 'Other')], max_length=20)),
                ('deadline_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='institutions.institution')),
            ],
            options={
                'db_table': 'deadlines',
                'ordering': ['deadline_date'],
            },
        ),
    ]
