# Generated by Django 5.0.6 on 2026-05-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '__first__'),
        ('institutions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('publisher', models.CharField(help_text='e.g. Stats SA, CHE, PayScale', max_length=200)),
                ('url', models.URLField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('methodology_note', models.TextField(blank=True)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary research vs. aggregator')),
            ],
            options={
                'db_table': 'outcome_data_sources',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sasic_code', models.CharField(blank=True, help_text='SA Standard Industrial Classification', max_length=10)),
                ('icon_emoji', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'db_table': 'employment_sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.PositiveSmallIntegerField(help_text='Year of the underlying study')),
                ('cohort_size', models.PositiveIntegerField(blank=True, help_text='Number of graduates surveyed', null=True)),
                ('employment_rate_6m', models.DecimalField(blank=True, decimal_places=2, help_text='% employed within 6 months of graduating', max_digits=5, null=True)),
                ('employment_rate_12m', models.DecimalField(blank=True, decimal_places=2, help_text='% employed within 12 months', max_digits=5, null=True)),
                ('further_study_rate', models.DecimalField(blank=True, decimal_places=2, help_text='% who pursued postgraduate or professional studies', max_digits=5, null=True)),
                ('self_employed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unemployment_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('salary_entry_p25', models.PositiveIntegerField(blank=True, help_text='Entry salary 25th percentile', null=True)),
                ('salary_entry_median', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_entry_p75', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_5yr_p25', models.PositiveIntegerField(blank=True, help_text='5-years experience 25th percentile', null=True)),
                ('salary_5yr_median', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_5yr_p75', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_10yr_median', models.PositiveIntegerField(blank=True, help_text='10-year median salary', null=True)),
                ('avg_time_to_first_job_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('job_satisfaction_score', models.DecimalField(blank=True, decimal_places=1, help_text='1-10 from graduate surveys', max_digits=3, null=True)),
                ('field_match_rate', models.DecimalField(blank=True, decimal_places=2, help_text='% working in their field of study', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.course')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_outcomes', to='institutions.institution')),
                ('sources', models.ManyToManyField(blank=True, related_name='outcomes', to='outcomes.datasource')),
            ],
            options={
                'db_table': 'course_outcomes',
                'ordering': ['-data_year', 'course'],
                'unique_together': {('course', 'institution', 'data_year')},
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_jse_listed', models.BooleanField(default=False)),
                ('headquarters_city', models.CharField(blank=True, max_length=100)),
                ('employee_count_range', models.CharField(blank=True, help_text='e.g. "10000+", "1000-5000"', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='employers/logos/')),
                ('website', models.URLField(blank=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outcomes.employmentsector')),
            ],
            options={
                'db_table': 'employers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('median_monthly_salary_zar', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='outcomes.courseoutcome')),
            ],
            options={
                'db_table': 'course_job_roles',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('grad_count_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_employers', to='outcomes.courseoutcome')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outcomes.employer')),
            ],
            options={
                'db_table': 'course_top_employers',
                'ordering': ['rank'],
                'unique_together': {('outcome', 'employer')},
            },
        ),
        migrations.CreateModel(
            name='CourseSectorBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_breakdown', to='outcomes.courseoutcome')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outcomes.employmentsector')),
            ],
            options={
                'db_table': 'course_sector_breakdowns',
                'ordering': ['rank'],
                'unique_together': {('outcome', 'sector')},
            },
        ),
    ]
