# Generated by Django 5.0.6 on 2026-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('provider', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('field', models.CharField(choices=[('engineering', 'Engineering & Technology'), ('health', 'Health Sciences'), ('business', 'Business & Commerce'), ('law', 'Law'), ('humanities', 'Humanities & Social Sciences'), ('science', 'Natural Sciences'), ('education', 'Education'), ('arts', 'Arts & Design'), ('agriculture', 'Agriculture'), ('ict', 'Information & Communication Technology'), ('built_environment', 'Built Environment'), ('any', 'Any Field')], default='any', max_length=30)),
                ('funding_type', models.CharField(choices=[('full', 'Full Bursary'), ('partial', 'Partial Bursary'), ('loan', 'Study Loan'), ('nsfas', 'NSFAS'), ('scholarship', 'Scholarship')], max_length=20)),
                ('coverage', models.JSONField(blank=True, default=list, help_text='What is covered (tuition, accommodation, etc.)')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('province', models.CharField(choices=[('GP', 'Gauteng'), ('WC', 'Western Cape'), ('KZN', 'KwaZulu-Natal'), ('EC', 'Eastern Cape'), ('MP', 'Mpumalanga'), ('LP', 'Limpopo'), ('NW', 'North West'), ('NC', 'Northern Cape'), ('FS', 'Free State'), ('ALL', 'All Provinces')], default='ALL', max_length=3)),
                ('eligibility', models.TextField(blank=True)),
                ('min_grade_average', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_household_income', models.PositiveIntegerField(blank=True, null=True)),
                ('application_url', models.URLField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bursaries/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_sponsored', models.BooleanField(default=False, help_text='Has an active sponsorship')),
                ('sponsor_priority', models.PositiveSmallIntegerField(default=0, help_text='Higher = more prominent placement')),
                ('sponsor_name', models.CharField(blank=True, max_length=200)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bursaries',
                'db_table': 'bursaries',
                'ordering': ['application_deadline', 'name'],
            },
        ),
    ]
