# Generated by Django 5.0.6 on 2026-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Remote CDN URL for the logo.'),
        ),
    ]
