# Generated by Django 5.0.6 on 2026-05-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '__first__'),
        ('documents', '0001_initial'),
        ('institutions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('conditional_offer', 'Conditional Offer'), ('firm_offer', 'Firm Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('waitlisted', 'Waitlisted')], default='draft', max_length=24)),
                ('application_reference', models.CharField(blank=True, help_text='Reference number from institution', max_length=100)),
                ('application_url', models.URLField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_priority', models.BooleanField(default=False, help_text='Star this as a top-choice application')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='courses.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-is_priority', 'deadline', '-created_at'],
                'unique_together': {('user', 'institution', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application')),
            ],
            options={
                'db_table': 'application_events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_copy', 'ID Document'), ('matric_certificate', 'Matric Certificate'), ('nsc_results', 'NSC Results'), ('proof_of_residence', 'Proof of Residence'), ('parent_income', 'Parent Income / Affidavit'), ('motivation_letter', 'Motivation Letter'), ('cv', 'CV'), ('reference_letter', 'Reference Letter'), ('proof_of_payment', 'Proof of Payment'), ('other', 'Other')], max_length=32)),
                ('is_required', models.BooleanField(default=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='applications.application')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_uses', to='documents.document')),
            ],
            options={
                'db_table': 'application_documents',
                'unique_together': {('application', 'document_type')},
            },
        ),
    ]
