# Generated by Django 5.0.6 on 2026-05-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('institution_type', models.CharField(choices=[('university', 'University'), ('university_of_technology', 'University of Technology'), ('tvet', 'TVET College'), ('private', 'Private College')], max_length=30)),
                ('province', models.CharField(choices=[('GP', 'Gauteng'), ('WC', 'Western Cape'), ('KZN', 'KwaZulu-Natal'), ('EC', 'Eastern Cape'), ('MP', 'Mpumalanga'), ('LP', 'Limpopo'), ('NW', 'North West'), ('NC', 'Northern Cape'), ('FS', 'Free State')], max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='institutions/covers/')),
                ('description', models.TextField(blank=True)),
                ('application_open', models.BooleanField(default=False)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True)),
                ('nsfas_accredited', models.BooleanField(default=False)),
                ('min_aps', models.PositiveSmallIntegerField(default=0)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'institutions',
                'ordering': ['name'],
            },
        ),
    ]
