# Generated by Django 5.0.6 on 2026-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='uses_extended_aps',
            field=models.BooleanField(default=False, help_text='True when the institution calculates APS using more than 6 subjects (e.g. includes Life Orientation) or uses a non-standard points scale. UP includes LO → max 49. Wits uses its own Faculty Points Score.'),
        ),
    ]
