# Generated by Django 5.0.6 on 2026-05-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_uses_extended_aps'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Remote CDN URL for the logo (used when no upload).'),
        ),
    ]
