# Generated by Django 5.0.6 on 2026-05-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('field', models.CharField(choices=[('engineering', 'Engineering & Technology'), ('health', 'Health Sciences'), ('business', 'Business & Commerce'), ('law', 'Law'), ('humanities', 'Humanities & Social Sciences'), ('science', 'Natural Sciences'), ('education', 'Education'), ('arts', 'Arts & Design'), ('agriculture', 'Agriculture'), ('ict', 'Information & Communication Technology'), ('built_environment', 'Built Environment'), ('other', 'Other')], max_length=30)),
                ('level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('advanced_diploma', 'Advanced Diploma'), ('degree', "Bachelor's Degree"), ('honours', 'Honours'), ('masters', 'Masters'), ('phd', 'PhD'), ('n1_n6', 'N1-N6 (TVET)'), ('nc_v', 'NC(V) (TVET)')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fees_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('career_opportunities', models.TextField(blank=True)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_aps', models.PositiveSmallIntegerField()),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True)),
                ('special_requirements', models.JSONField(blank=True, default=list)),
                ('subject_requirements', models.JSONField(blank=True, default=list)),
                ('available_spaces', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='courses.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='institutions.institution')),
            ],
            options={
                'db_table': 'course_offerings',
                'unique_together': {('course', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='SubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('min_level', models.PositiveSmallIntegerField(default=4)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reqs', to='courses.courseoffering')),
            ],
            options={
                'db_table': 'subject_requirements',
            },
        ),
    ]
