# Generated by Django 5.0.6 on 2026-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='campus',
            field=models.CharField(blank=True, help_text='Campus or campus code, e.g. "APK", "Soweto"', max_length=100),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='programme_code',
            field=models.CharField(blank=True, help_text="Institution-specific code (e.g. UJ's B34A5Q)", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'institution', 'campus')},
        ),
    ]
