# Generated by Django 5.0.6 on 2026-05-16 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseoffering_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'Viewed'), ('save', 'Saved'), ('apply', 'Applied')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_interactions',
                'indexes': [models.Index(fields=['user', 'course'], name='course_inte_user_id_a005db_idx'), models.Index(fields=['course', 'kind'], name='course_inte_course__b41f4e_idx')],
            },
        ),
    ]
