# Generated by Django 5.0.6 on 2026-05-07 16:06

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_copy', 'ID Document'), ('passport', 'Passport'), ('matric_certificate', 'Matric Certificate'), ('nsc_results', 'NSC Results / Report Card'), ('proof_of_residence', 'Proof of Residence'), ('parent_income', 'Parent Income / Affidavit'), ('motivation_letter', 'Motivation Letter'), ('cv', 'CV / Resume'), ('reference_letter', 'Reference Letter'), ('proof_of_payment', 'Proof of Payment'), ('birth_certificate', 'Birth Certificate'), ('photo', 'Passport Photo'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.documents.models.encrypted_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified for authenticity')),
                ('is_encrypted', models.BooleanField(default=True)),
                ('expires_at', models.DateField(blank=True, help_text='When this document needs to be re-uploaded (e.g. proof of residence)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('attach', 'Attach to application'), ('delete', 'Delete')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
