# Generated by Django 5.0.6 on 2026-05-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show me to potential roommates')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not', 'Prefer not to say')], max_length=12)),
                ('target_city', models.CharField(blank=True, max_length=100)),
                ('move_in_month', models.DateField(blank=True, help_text='Earliest move-in date', null=True)),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_schedule', models.CharField(blank=True, choices=[('early', 'Early bird (before 10pm)'), ('average', 'Average (10pm–12am)'), ('night_owl', 'Night owl (after 12am)')], max_length=12)),
                ('cleanliness', models.CharField(blank=True, choices=[('very_clean', 'Very clean'), ('clean', 'Clean'), ('average', 'Average'), ('relaxed', 'Relaxed')], max_length=12)),
                ('social_level', models.CharField(blank=True, choices=[('introvert', 'Introvert'), ('balanced', 'Balanced'), ('extrovert', 'Extrovert')], max_length=12)),
                ('study_habits', models.CharField(blank=True, choices=[('quiet', 'Need quiet space'), ('flexible', 'Flexible'), ('library', 'Study elsewhere')], max_length=12)),
                ('smokes', models.BooleanField(default=False)),
                ('drinks', models.BooleanField(default=False)),
                ('has_pets', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('prefers_same_gender', models.BooleanField(default=False)),
                ('prefers_non_smoker', models.BooleanField(default=True)),
                ('prefers_no_pets', models.BooleanField(default=False)),
                ('age_range_min', models.PositiveSmallIntegerField(default=17)),
                ('age_range_max', models.PositiveSmallIntegerField(default=30)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roommate_profiles',
            },
        ),
        migrations.CreateModel(
            name='RoommateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='roommates.roommateprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='roommates.roommateprofile')),
            ],
            options={
                'db_table': 'roommate_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('liked', 'Liked'), ('matched', 'Matched'), ('passed', 'Passed'), ('blocked', 'Blocked')], default='liked', max_length=10)),
                ('score', models.FloatField(default=0.0, help_text='Compatibility score 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to='roommates.roommateprofile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='roommates.roommateprofile')),
            ],
            options={
                'db_table': 'roommate_matches',
                'unique_together': {('from_profile', 'to_profile')},
            },
        ),
    ]
